apiVersion: v1
kind: pod
metadata:
  name: mongo-db
  labels: 
    app: pv-azure
    env: test
spec:
  containers:
    - image: mongo
      name: mongodb
      volumeMount: 
        - name: volume
          mountPath: /data/db
      ports:
        - containerPort: 27017
          protocol: TCP
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azure-managed-disk
