apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default # this built-in storage class using azureDisk in azureCloud
  resources:
    requests:
      storage: 1Gi