apiVersion: v1
kind: Pod
metadata:
  name: fortune
  labels:
    app: fortune-app
spec:
  containers:
    - name: html-generator
      image: ycharki/fortune
      volumeMounts:
        - name: html
          mountPath: /var/htdocs
    - name: web-server
      image: nginx:alpine
      volumeMounts: 
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly: true
      ports:
        - containerPort: 80
          protocol: TCP
  volumes:
    - name: html
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata: 
  name: fortune-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: fortune-app